### ISSUE TITLE
Broken pipe error

### ISSUE THREAD

**Issue by ericwoodall** [mpcarter/dbt-vertica#3] opened 2021-02-18 19:29 UTC
Hey Matthew!  I am having an issue with the dbt-vertica adapter.  If I have a dbt model that runs longer than ~5 minutes, it fails with a broken pipe error:
Unhandled error while executing model.embold_prototype.ssm_ccm_member_months
[Errno 32] Broken pipe

I have tried changing adding timeout values in the profiles.yml file but nothing works.
The errors that we are seeing on the Vertica server have to do with load balancing.

**Comment by mpcarter** [comment] 2021-03-11 03:19
Hi Eric! Hmm, hard to say what the cause is. 😕  It's usually a good idea to include details like what version of software you are using, OS, etc. 

I know I have some models that can take more than 30 minutes to run and they work fine. 

If you have a dedicated load balancer in front of your vertica cluster, then maybe it is forcing a connection timeout after 5 minutes?

Is there any other pertinent info in the dbt logs?

Have you tried copying the compiled SQL from dbt and running it manually on your database to see if it can run to completion? 

Sorry for the late reply. The notification to my gmail got buried in a sea of emails.

**Comment by mattberns** [comment] 2021-03-26 14:13
@mpcarter It looks like after deeper research, that our TCP connections are idle for 60 minutes, and we are getting our queries killed without any packets going over the wire. 

Other tools have solved this with a keepalive. Basically sending a `SELECT 1` query every N minutes. @mpcarter I will work on this and submit a PR unless you have any suggestions.

**Comment by mpcarter** [comment] 2021-05-21 14:23
@mattberns I'm not sure I know enough about TCP and keepalive to say one way or another. But I also would think that kind of functionality would probably go to dbt-core, not this vertica adapter?

**Comment by ahedengren** [comment] 2022-02-25 19:00
Hi @mattberns,

Were you able to resolve this issue?

**Comment by ahedengren** [comment] 2022-03-15 07:35
Hi @mattberns 

I believe this is either a network setting, or an implementation detail for [vertica_python](https://github.com/vertica/vertica-python) to handle keepalives (as mentioned above).

The dbt Vertica adapter implements vertica_python for connection, then macros using JINJA the SQL dialect needed.

I'm going to close this, and if it's still posing an issue, to raid a ticket for the vertica_python team.

Thanks
/Andrew

**Closed by ahedengren** 2022-03-15 07:35 UTC
